#!/bin/bash
# Script for generating Fedora releng release signing tickets.  Generated by
# https://github.com/coreos/repo-templates; do not edit downstream.

set -euo pipefail

usage() {
    echo "Usage: $0 test <version-release> <dir>"
    echo "Usage: $0 ticket <version-release>"
    exit 1
}

make_script() {
    sed -e "s/@@VERSION@@/$ver/g" -e "s/@@RELEASE@@/$rel/g" <<'EOF'
#!/bin/bash
set -eux -o pipefail

# Use the Fedora {{ current_fedora }} key for the detached signatures
KEYTOSIGNWITH='fedora-{{ current_fedora }}'

VR='@@VERSION@@-@@RELEASE@@.fc{{ current_fedora }}'
RPMKEY='{{ current_fedora_signing_key | lower }}' # Fedora {{ current_fedora }} key

do_sign() {
    # Sign with sigul unless FAKESIGN=1
    if [ ${FAKESIGN:-0} != 1 ]; then
        sigul sign-data -a $KEYTOSIGNWITH "$1" -o "$1.asc"
    else
        echo INVALID > "$1.asc"
    fi
}
{% for target in signing_targets %}

# Grab the {{ target.base }} binaries out of the redistributable rpm
rpm="{{ target.base }}-redistributable-${VR}.noarch.rpm"
koji download-build --key $RPMKEY --rpm $rpm
# rpm -Kv may exit non-zero (e.g. NOKEY) if the public key is not
# installed locally, so inspect its output instead of its exit code.
verify_output=$(rpm -Kv "$rpm" 2>&1 || true)
if ! grep -qi "key ID .*${RPMKEY}" <<< "$verify_output"; then
    echo "ERROR: $rpm is not signed with expected key ${RPMKEY}"
    echo "$verify_output"
    exit 1
fi
rpm2cpio $rpm | cpio -idv './usr/share/{{ target.package }}/{{ target.base }}-*'

# Rename the {{ target.base }} binaries
{%- for packaged_variant, variant in target.variants %}
mv usr/share/{{ target.package }}/{{ target.base }}-{{ packaged_variant }} \
    {{ target.base }}-{{ variant }}
{%- endfor %}

# Sign the {{ target.base }} binaries
{%- for _, variant in target.variants %}
do_sign {{ target.base }}-{{ variant }}
{%- endfor %}
{% endfor %}

# Fix permissions and clean up
chmod go+r *.asc
{%- for target in signing_targets %}
rm {{ target.base }}-redistributable-*.rpm
{%- endfor %}
{%- for target in signing_targets %}
rmdir ./usr/share/{{ target.package }}
{%- endfor %}
rmdir ./usr/share ./usr
EOF
}

make_ticket() {
    sed "s/@@VERSION@@/$ver/g" <<'EOF'
TITLE: Create detached signatures for the {{ fedora_package }} @@VERSION@@ release

Please create detached signatures for the binaries we will upload to GitHub for the `{{ fedora_package }}` @@VERSION@@ release.  This is a manual process for now, pending the automation discussed in https://pagure.io/robosignatory/issue/53 and https://github.com/coreos/fedora-coreos-tracker/issues/335.

The binaries themselves have been built in koji.  Here is a small script to grab all of the rpms and the files out of the rpms and name them appropriately:

```
EOF
    make_script
    cat <<'EOF'
```

After running this you should end up with a directory with files in it like:

{# create array of all variant values for sorting #}
{% set_global all_variants = [] %}
{% for target in signing_targets %}
{% for _, variant in target.variants %}
{% set_global all_variants = all_variants | concat(with=target.base ~ "-" ~ variant) %}
{% endfor %}
{% endfor %}

```
$ ls -1
{%- for variant in all_variants | sort %}
{{ variant }}
{{ variant }}.asc
{%- endfor %}
```
EOF
}

[ "$#" -lt 2 ] && usage
cmd="$1"
ver="$2"
# Disallow version with preceding "v"
echo "$ver" | grep -q "v" && usage
# Require version-release
echo "$ver" | grep -q "-" || usage
rel="${ver#*-}"
ver="${ver%%-*}"

case "$cmd" in
test)
    [ "$#" != 3 ] && usage
    dir="$3"
    mkdir "$dir"
    make_script > "$dir/script"
    cd "$dir" && FAKESIGN=1 bash script
    ;;
ticket)
    make_ticket
    ;;
*)
    usage
    ;;
esac
