#!/bin/bash
# Script for generating Fedora releng release signing tickets.  Generated by
# https://github.com/coreos/repo-templates; do not edit downstream.

set -euo pipefail

usage() {
    echo "Usage: $0 test <version-release> <dir>"
    echo "Usage: $0 ticket <version-release>"
    exit 1
}

make_script() {
    sed -e "s/@@VERSION@@/$ver/g" -e "s/@@RELEASE@@/$rel/g" <<'EOF'
#!/bin/bash
set -eux -o pipefail

# Use the Fedora {{ current_fedora }} key for the detached signatures
KEYTOSIGNWITH='fedora-{{ current_fedora }}'

VR='@@VERSION@@-@@RELEASE@@.fc{{ current_fedora }}'
RPMKEY='{{ current_fedora_signing_key | lower }}' # Fedora {{ current_fedora }} key

do_sign() {
    # Sign with sigul unless FAKESIGN=1
    if [ ${FAKESIGN:-0} != 1 ]; then
        sigul sign-data -a $KEYTOSIGNWITH "$1" -o "$1.asc"
    else
        echo INVALID > "$1.asc"
    fi
}

# Grab the binaries out of the redistributable rpm
rpm="{{ signing_base }}-redistributable-${VR}.noarch.rpm"
koji download-build --key $RPMKEY --rpm $rpm
rpm -Kv "$rpm" 2>&1 | grep -qi "${RPMKEY}" # Verify the output has the key in it
rpm2cpio $rpm | cpio -idv './usr/share/{{ fedora_package }}/{{ signing_base }}-*'

# Rename the binaries
{%- for packaged_variant, variant in signing_variants %}
mv usr/share/{{ fedora_package }}/{{ signing_base }}-{{ packaged_variant }} \
    {{ signing_base }}-{{ variant }}
{%- endfor %}

# Sign them
{%- for _, variant in signing_variants %}
do_sign {{ signing_base }}-{{ variant }}
{%- endfor %}

# Fix permissions and clean up
chmod go+r *.asc
rm $rpm; rmdir ./usr/share/{{ fedora_package }}; rmdir ./usr/share; rmdir ./usr
EOF
}

make_ticket() {
    sed "s/@@VERSION@@/$ver/g" <<'EOF'
TITLE: Create detached signatures for the {{ fedora_package }} @@VERSION@@ release

Please create detached signatures for the binaries we will upload to GitHub for the `{{ fedora_package }}` @@VERSION@@ release.  This is a manual process for now, pending the automation discussed in https://pagure.io/robosignatory/issue/53 and https://github.com/coreos/fedora-coreos-tracker/issues/335.

The binaries themselves have been built in koji.  Here is a small script to grab all of the rpms and the files out of the rpms and name them appropriately:

```
EOF
    make_script
    cat <<'EOF'
```

After running this you should end up with a directory with files in it like:

{# create array of map values for sorting #}
{% set_global variant_values = [] %}
{% for _, variant in signing_variants %}
{% set_global variant_values = variant_values | concat(with=variant) %}
{% endfor %}

```
$ ls -1
{%- for variant in variant_values | sort %}
{{ signing_base }}-{{ variant }}
{{ signing_base }}-{{ variant }}.asc
{%- endfor %}
```
EOF
}

[ "$#" -lt 2 ] && usage
cmd="$1"
ver="$2"
# Disallow version with preceding "v"
echo "$ver" | grep -q "v" && usage
# Require version-release
echo "$ver" | grep -q "-" || usage
rel="${ver#*-}"
ver="${ver%%-*}"

case "$cmd" in
test)
    [ "$#" != 3 ] && usage
    dir="$3"
    mkdir "$dir"
    make_script > "$dir/script"
    cd "$dir" && FAKESIGN=1 bash script
    ;;
ticket)
    make_ticket
    ;;
*)
    usage
    ;;
esac
